### PR TITLE
Upped macOS version requirements to v11 to allow compilation on macOS

### PR DESCRIPTION
**Pull request by Diggory**
SRP requires 10_15 and HKDF is only available in 11

### CODE REVIEW

**Comment by Diggory** [comment]
Hi @Bouke, How do I get the SwiftLink check to complete?  Thanks.

**Comment by Bouke** [comment]
Did you remove your changes from your master branch? There are no changed files in this PR. The SwiftLint check should run automatically, let's see what happens when you add commits.

What are you trying to change? `Package.swift` already has a v11 requirement.

**Comment by Diggory** [comment]
Huh, that's weird - I seem to have changed the V11 from your master to V10_15 then back to V11. 
No idea why I did that!

**Comment by Diggory** [comment]
Ahh, I see what happened -  I tried to depend on HAP using the most recently tagged release.  That failed because it didn't have any platforms minimum requirements.  So I assumed that main was the same, but main is not the same.

Any chance of tagging a new release so we don't have to depend on a moving target?  #163 

p.s. thanks for all your work on HAP - it's very useful.  So useful that I [Nominated it for the Package Community Showcase](https://forums.swift.org/t/nominations-for-the-packages-community-showcase-on-swift-org/68168/4).

**Pull request closed without merging**
