### PR TITLE
Support Swift 5.0

### PR DESCRIPTION
**Pull request by Bouke**

### CODE REVIEW

**Comment by gbrooker** [comment]
Great. How about dropping Evergreen.logger and replacing with [swift-log](https://github.com/apple/swift-log)

**Comment by Bouke** [comment]
swift-log would be great, however it target Swift 5, and 4.2 is still the latest and greatest for ARM. So when that’s resolved, I’m all for switching to swift-log.

**Comment by gbrooker** [comment]
Indeed, as part of the move to swift 5. 

I see that NIO2 is released with Swift 5, will that have much impact on your NIO code in HAP ?

**Comment by Bouke** [comment]
I dunno, haven't investigated the differences. NIO2 also targets Swift 5, which prevents me from targetting that version just yet.

**Pull request merged**
